# Generated by Django 5.2.7 on 2026-02-26 13:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventarioDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Inventario Diario',
                'verbose_name_plural': 'Inventarios Diarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('cierre', 'Cierre Diario')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_nuevo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('referencia', models.CharField(blank=True, help_text='Número de pedido, ajuste, etc.', max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_stock', to='producto.producto')),
            ],
            options={
                'verbose_name': 'Historial de Stock',
                'verbose_name_plural': 'Historial de Stock',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_control', models.CharField(choices=[('peso', 'Por Peso (kg)'), ('unidad', 'Por Unidad')], default='unidad', max_length=10)),
                ('inventario_inicial', models.DecimalField(decimal_places=2, help_text='Stock al inicio del día', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('consumo_automatico', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Consumo registrado automáticamente por ventas', max_digits=10)),
                ('inventario_final', models.DecimalField(blank=True, decimal_places=2, help_text='Stock real al final del día (conteo físico)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('ajuste_manual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ajuste manual por diferencias, mermas, etc.', max_digits=10)),
                ('motivo_ajuste', models.CharField(blank=True, help_text='Razón del ajuste (merma, robo, error, etc.)', max_length=200, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('inventario_diario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventario.inventariodiario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inventario', to='producto.producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['producto__nombre'],
                'unique_together': {('inventario_diario', 'producto')},
            },
        ),
    ]
