# Generated by Django 5.2.7 on 2026-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialstock',
            name='referencia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddConstraint(
            model_name='inventariodiario',
            constraint=models.UniqueConstraint(fields=('fecha',), name='unique_inventario_por_fecha'),
        ),
    ]
