# Generated by Django 5.2.7 on 2026-02-26 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('hora', 'Por Hora'), ('dia', 'Por Día')], default='dia', max_length=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, help_text='Valor por hora o día', max_digits=10)),
                ('cantidad', models.DecimalField(decimal_places=2, help_text='Horas o días trabajados', max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('fecha_inicio', models.DateField(help_text='Fecha de inicio del período')),
                ('fecha_fin', models.DateField(help_text='Fecha de fin del período')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.now, help_text='Fecha de pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Nómina',
                'verbose_name_plural': 'Nóminas',
                'ordering': ['-fecha_pago', '-fecha_creacion'],
            },
        ),
    ]
