# Generated by Django 5.2.7 on 2026-03-05 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tamanio_kb', models.PositiveIntegerField(default=0)),
                ('drive_file_id', models.CharField(blank=True, max_length=255)),
                ('exitoso', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Registro de Backup',
                'verbose_name_plural': 'Registros de Backups',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
