# Generated by Django 5.2.7 on 2026-02-26 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario', null=True, upload_to='perfiles/', verbose_name='foto de perfil'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cargo',
            field=models.CharField(blank=True, choices=[('mesero', 'Mesero'), ('administrador', 'Administrador'), ('cocinero', 'Cocinero'), ('parrilla', 'Parrilla'), ('cajera', 'Cajera')], default='operador', max_length=50, verbose_name='cargo'),
        ),
    ]
