# Generated by Django 5.2.7 on 2026-02-26 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('venta', 'Informe de Ventas'), ('compra', 'Informe de Compras'), ('nomina', 'Informe de Nómina'), ('personalizado', 'Otro')], max_length=20)),
                ('fecha_creacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
    ]
