# Generated by Django 5.2.7 on 2026-03-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
        ('venta', '0002_venta_cliente_venta_cliente_factura_venta_mesero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaitem',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_items', to='producto.producto'),
        ),
    ]
