# Generated by Django 5.2.7 on 2026-03-13 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_vistaconfig'),
        ('venta', '0003_ventaitem_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaitem',
            name='producto',
        ),
        migrations.AddField(
            model_name='ventaitem',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_items', to='menu.menu'),
        ),
    ]
