# Generated by Django 5.2.7 on 2026-03-13 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_remove_ventaitem_producto_ventaitem_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaitem',
            name='menu',
        ),
    ]
