# Generated by Django 5.2.7 on 2026-02-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(choices=[('peso', 'Por Peso (kg, g, L, ml...)'), ('unidad', 'Por Unidad (piezas, cajas...)')], default='unidad', help_text='Define si esta unidad es por peso/volumen o por conteo', max_length=10)),
            ],
        ),
    ]
