# Generated by Django 5.2.7 on 2026-02-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0001_initial'),
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VistaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('parrilla', 'Parrilla'), ('cocina', 'Cocina')], max_length=20, unique=True, verbose_name='Área de Cocina')),
                ('categorias_activas', models.ManyToManyField(blank=True, related_name='vistas_config', to='categoria.categoria', verbose_name='Categorías visibles en esta vista')),
            ],
            options={
                'verbose_name': 'Configuración de Vista',
                'verbose_name_plural': 'Configuraciones de Vista',
            },
        ),
    ]
