# Generated by Django 5.2.7 on 2026-02-26 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('producto', '0001_initial'),
        ('unidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
        ),
        migrations.CreateModel(
            name='PlatoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('plato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plato.plato')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos_producto', to='producto.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unidad.unidad')),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='productos',
            field=models.ManyToManyField(related_name='platos', through='plato.PlatoProducto', to='producto.producto'),
        ),
    ]
